blitz: blitz/array-impl.h File Reference
array-impl.h File Reference
#include <blitz/blitz.h>
#include <blitz/memblock.h>
#include <blitz/range.h>
#include <blitz/tinyvec.h>
#include <blitz/indexexpr.h>
#include <blitz/prettyprint.h>
#include <blitz/array/slice.h>
#include <blitz/array/map.h>
#include <blitz/array/multi.h>
#include <blitz/array/domain.h>
#include <blitz/array/storage.h>
#include <blitz/array/iter.h>
#include <blitz/array/fastiter.h>
#include <blitz/array/expr.h>
#include <blitz/array/methods.cc>
#include <blitz/array/eval.cc>
#include <blitz/array/ops.cc>
#include <blitz/array/io.cc>
#include <blitz/array/et.h>
#include <blitz/array/reduce.h>
#include <blitz/array/interlace.cc>
#include <blitz/array/resize.cc>
#include <blitz/array/slicing.cc>
#include <blitz/array/cycle.cc>
#include <blitz/array/complex.cc>
#include <blitz/array/zip.h>
#include <blitz/array/where.h>
#include <blitz/array/indirect.h>
#include <blitz/array/stencils.h>
Classes
class ArrayIterator< T_numtype, N_rank >
class ConstArrayIterator< T_numtype, N_rank >
class FastArrayIterator< T_numtype, N_rank >
class _bz_ArrayExpr< P_expr >
class IndirectArray< T_array, T_index >
class Array< P_numtype, N_rank >
Functions
template<typename P_numtype , int N_rank>
void swap (Array< P_numtype, N_rank > &, Array< P_numtype, N_rank > &)
template<typename P_numtype , int N_rank>
void find (Array< TinyVector< int, N_rank >, 1 > &, const Array< P_numtype, N_rank > &)
template<typename T_numtype >
ostream & operator<< (ostream &, const Array< T_numtype, 1 > &)
template<typename T_numtype >
ostream & operator<< (ostream &, const Array< T_numtype, 2 > &)
template<typename T_numtype , int N_rank>
ostream & operator<< (ostream &, const Array< T_numtype, N_rank > &)
template<typename T_numtype , int N_rank>
istream & operator>> (istream &is, Array< T_numtype, N_rank > &x)
template<typename P_expr >
void find (Array< TinyVector< int, P_expr::rank >, 1 > &indices, const _bz_ArrayExpr< P_expr > &expr)
Variables
const int firstRank = 0
const int secondRank = 1
const int thirdRank = 2
const int fourthRank = 3
const int fifthRank = 4
const int sixthRank = 5
const int seventhRank = 6
const int eighthRank = 7
const int ninthRank = 8
const int tenthRank = 9
const int eleventhRank = 10
const int firstDim = 0
const int secondDim = 1
const int thirdDim = 2
const int fourthDim = 3
const int fifthDim = 4
const int sixthDim = 5
const int seventhDim = 6
const int eighthDim = 7
const int ninthDim = 8
const int tenthDim = 9
const int eleventhDim = 10
Function Documentation
template<typename P_numtype , int N_rank> void find (Array< TinyVector< int, N_rank >, 1 > & indices, const Array< P_numtype, N_rank > & exprVals)
References Array< P_numtype, N_rank >::begin(), Array< P_numtype, N_rank >::end(), j, and Array< P_numtype, N_rank >::size().
Referenced by find().
template<typename P_expr > void find (Array< TinyVector< int, P_expr::rank >, 1 > & indices, const _bz_ArrayExpr< P_expr > & expr)
References find().
template<typename T_numtype > ostream& operator<< (ostream & , const Array< T_numtype, 1 > &)
template<typename T_numtype > ostream& operator<< (ostream & , const Array< T_numtype, 2 > &)
template<typename T_numtype , int N_rank> ostream& operator<< (ostream & , const Array< T_numtype, N_rank > &)
template<typename T_numtype , int N_rank> istream& operator>> (istream & is, Array< T_numtype, N_rank > & x)
template<typename P_numtype , int N_rank> void swap (Array< P_numtype, N_rank > & a, Array< P_numtype, N_rank > & b)
References Array< P_numtype, N_rank >::reference().
Variable Documentation
const int eighthDim = 7
const int eighthRank = 7
const int eleventhDim = 10
const int eleventhRank = 10
const int fifthDim = 4
const int fifthRank = 4
const int firstDim = 0
const int firstRank = 0
const int fourthDim = 3
const int fourthRank = 3
const int ninthDim = 8
const int ninthRank = 8
const int secondDim = 1
const int secondRank = 1
const int seventhDim = 6
const int seventhRank = 6
const int sixthDim = 5
const int sixthRank = 5
const int tenthDim = 9
const int tenthRank = 9
const int thirdDim = 2
const int thirdRank = 2