blitz: Symmetric Class Reference
Symmetric Class Reference
#include <matsymm.h>
Public Types
typedef SymmetricIterator T_iterator
Public Member Functions
Symmetric ()
Symmetric (unsigned size)
Symmetric (unsigned rows, unsigned cols)
unsigned columns () const
unsigned coordToOffset (unsigned i, unsigned j) const
unsigned firstInRow (unsigned i) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
unsigned lastInRow (unsigned i) const
unsigned firstInCol (unsigned j) const
unsigned lastInCol (unsigned j) const
bool inRange (unsigned i, unsigned j) const
unsigned numElements () const
unsigned rows () const
void resize (unsigned size)
void resize (unsigned rows, unsigned cols)
Private Attributes
unsigned size_
Member Typedef Documentation
typedef SymmetricIterator Symmetric::T_iterator
Constructor & Destructor Documentation
Symmetric::Symmetric () inline
Symmetric::Symmetric (unsigned size) inline
Symmetric::Symmetric (unsigned rows, unsigned cols) inline
Member Function Documentation
unsigned Symmetric::columns () const inline
References size_.
unsigned Symmetric::coordToOffset (unsigned i, unsigned j) const inline
References inRange().
Referenced by get().
unsigned Symmetric::firstInCol (unsigned j) const inline
References j.
unsigned Symmetric::firstInRow (unsigned i) const inline
template<typename T_numtype > T_numtype Symmetric::get (const T_numtype *restrict data, unsigned i, unsigned j) const inline
References coordToOffset(), i, inRange(), and j.
template<typename T_numtype > T_numtype& Symmetric::get (T_numtype *restrict data, unsigned i, unsigned j) inline
References coordToOffset(), i, inRange(), and j.
bool Symmetric::inRange (unsigned i, unsigned j) const inline
References size_.
Referenced by coordToOffset(), and get().
unsigned Symmetric::lastInCol (unsigned j) const inline
References size_.
unsigned Symmetric::lastInRow (unsigned i) const inline
References i.
unsigned Symmetric::numElements () const inline
References size_.
void Symmetric::resize (unsigned size) inline
References size_.
void Symmetric::resize (unsigned rows, unsigned cols) inline
References rows(), and size_.
unsigned Symmetric::rows () const inline
References size_.
Referenced by resize().
Member Data Documentation
unsigned Symmetric::size_ private
Referenced by columns(), inRange(), lastInCol(), numElements(), resize(), and rows().
The documentation for this class was generated from the following file:
blitz/matsymm.h