blitz: UpperTriangular Class Reference
UpperTriangular Class Reference
#include <matutri.h>
Public Types
typedef UpperTriangularIterator T_iterator
Public Member Functions
UpperTriangular ()
UpperTriangular (unsigned size)
UpperTriangular (unsigned rows, unsigned cols)
unsigned columns () const
unsigned coordToOffset (unsigned i, unsigned j) const
unsigned firstInRow (unsigned i) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
unsigned lastInRow (unsigned i) const
unsigned firstInCol (unsigned j) const
unsigned lastInCol (unsigned j) const
bool inRange (const unsigned i, const unsigned j) const
unsigned numElements () const
unsigned rows () const
void resize (const unsigned size)
void resize (const unsigned rows, const unsigned cols)
Private Attributes
unsigned size_
Member Typedef Documentation
typedef UpperTriangularIterator UpperTriangular::T_iterator
Constructor & Destructor Documentation
UpperTriangular::UpperTriangular () inline
UpperTriangular::UpperTriangular (unsigned size) inline
UpperTriangular::UpperTriangular (unsigned rows, unsigned cols) inline
Member Function Documentation
unsigned UpperTriangular::columns () const inline
References size_.
unsigned UpperTriangular::coordToOffset (unsigned i, unsigned j) const inline
References inRange().
Referenced by get().
unsigned UpperTriangular::firstInCol (unsigned j) const inline
unsigned UpperTriangular::firstInRow (unsigned i) const inline
template<typename T_numtype > T_numtype UpperTriangular::get (const T_numtype *restrict data, unsigned i, unsigned j) const inline
References coordToOffset(), i, inRange(), j, and ZeroElement< P_numtype >::zero().
template<typename T_numtype > T_numtype& UpperTriangular::get (T_numtype *restrict data, unsigned i, unsigned j) inline
References coordToOffset(), i, inRange(), j, and ZeroElement< P_numtype >::zero().
bool UpperTriangular::inRange (const unsigned i, const unsigned j) const inline
References size_.
Referenced by coordToOffset(), and get().
unsigned UpperTriangular::lastInCol (unsigned j) const inline
References j.
unsigned UpperTriangular::lastInRow (unsigned i) const inline
References size_.
unsigned UpperTriangular::numElements () const inline
References size_.
void UpperTriangular::resize (const unsigned size) inline
References size_.
void UpperTriangular::resize (const unsigned rows, const unsigned cols) inline
References rows(), and size_.
unsigned UpperTriangular::rows () const inline
References size_.
Referenced by resize().
Member Data Documentation
unsigned UpperTriangular::size_ private
Referenced by columns(), inRange(), lastInRow(), numElements(), resize(), and rows().
The documentation for this class was generated from the following file:
blitz/matutri.h