blitz: Diagonal Class Reference
Diagonal Class Reference
#include <matdiag.h>
Public Types
typedef DiagonalIterator T_iterator
Public Member Functions
Diagonal ()
Diagonal (const unsigned size)
Diagonal (const unsigned rows, const unsigned cols)
unsigned columns () const
unsigned coordToOffset (const unsigned i, const unsigned j) const
unsigned firstInRow (const unsigned i) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, const unsigned i, const unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, const unsigned i, const unsigned j)
unsigned lastInRow (const unsigned i) const
unsigned firstInCol (const unsigned j) const
unsigned lastInCol (const unsigned j) const
bool inRange (const unsigned i, const unsigned j) const
unsigned numElements () const
unsigned rows () const
void resize (const unsigned size)
void resize (const unsigned rows, const unsigned cols)
Private Attributes
unsigned size_
Member Typedef Documentation
typedef DiagonalIterator Diagonal::T_iterator
Constructor & Destructor Documentation
Diagonal::Diagonal () inline
Diagonal::Diagonal (const unsigned size) inline
Diagonal::Diagonal (const unsigned rows, const unsigned cols) inline
Member Function Documentation
unsigned Diagonal::columns () const inline
References size_.
unsigned Diagonal::coordToOffset (const unsigned i, const unsigned j) const inline
References i, and inRange().
Referenced by get().
unsigned Diagonal::firstInCol (const unsigned j) const inline
References j.
unsigned Diagonal::firstInRow (const unsigned i) const inline
References i.
template<typename T_numtype > T_numtype Diagonal::get (const T_numtype *restrict data, const unsigned i, const unsigned j) const inline
References coordToOffset(), i, inRange(), j, and ZeroElement< P_numtype >::zero().
template<typename T_numtype > T_numtype& Diagonal::get (T_numtype *restrict data, const unsigned i, const unsigned j) inline
References coordToOffset(), i, inRange(), j, and ZeroElement< P_numtype >::zero().
bool Diagonal::inRange (const unsigned i, const unsigned j) const inline
References size_.
Referenced by coordToOffset(), and get().
unsigned Diagonal::lastInCol (const unsigned j) const inline
References j.
unsigned Diagonal::lastInRow (const unsigned i) const inline
References i.
unsigned Diagonal::numElements () const inline
References size_.
void Diagonal::resize (const unsigned size) inline
References size_.
void Diagonal::resize (const unsigned rows, const unsigned cols) inline
References rows(), and size_.
unsigned Diagonal::rows () const inline
References size_.
Referenced by resize().
Member Data Documentation
unsigned Diagonal::size_ private
Referenced by columns(), inRange(), numElements(), resize(), and rows().
The documentation for this class was generated from the following file:
blitz/matdiag.h