blitz: ReduceMinIndex< P_sourcetype > Class Template Reference
ReduceMinIndex< P_sourcetype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef int T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceMinIndex ()
ReduceMinIndex (T_resulttype min)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, int index)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = true
static const bool canProvideInitialValue = false
Protected Attributes
T_sourcetype min_
int index_
Member Typedef Documentation
template<typename P_sourcetype > typedef T_resulttype ReduceMinIndex< P_sourcetype >::T_numtype
template<typename P_sourcetype > typedef int ReduceMinIndex< P_sourcetype >::T_resulttype
template<typename P_sourcetype > typedef P_sourcetype ReduceMinIndex< P_sourcetype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype > ReduceMinIndex< P_sourcetype >::ReduceMinIndex () inline
References ReduceMinIndex< P_sourcetype >::reset().
template<typename P_sourcetype > ReduceMinIndex< P_sourcetype >::ReduceMinIndex (T_resulttype min) inline
References ReduceMinIndex< P_sourcetype >::reset().
Member Function Documentation
template<typename P_sourcetype > static const char* ReduceMinIndex< P_sourcetype >::name () inline static
template<typename P_sourcetype > bool ReduceMinIndex< P_sourcetype >::operator() (T_sourcetype x) inline
template<typename P_sourcetype > bool ReduceMinIndex< P_sourcetype >::operator() (T_sourcetype x, int index) inline
References ReduceMinIndex< P_sourcetype >::index_, and ReduceMinIndex< P_sourcetype >::min_.
template<typename P_sourcetype > void ReduceMinIndex< P_sourcetype >::reset () inline
References ReduceMinIndex< P_sourcetype >::index_, and ReduceMinIndex< P_sourcetype >::min_.
Referenced by ReduceMinIndex< P_sourcetype >::ReduceMinIndex(), and ReduceMinIndex< P_sourcetype >::reset().
template<typename P_sourcetype > void ReduceMinIndex< P_sourcetype >::reset (T_resulttype) inline
References ReduceMinIndex< P_sourcetype >::reset().
template<typename P_sourcetype > T_resulttype ReduceMinIndex< P_sourcetype >::result (int) inline
References ReduceMinIndex< P_sourcetype >::index_.
Member Data Documentation
template<typename P_sourcetype > const bool ReduceMinIndex< P_sourcetype >::canProvideInitialValue = false static
template<typename P_sourcetype > int ReduceMinIndex< P_sourcetype >::index_ protected
Referenced by ReduceMinIndex< P_sourcetype >::operator()(), ReduceMinIndex< P_sourcetype >::reset(), and ReduceMinIndex< P_sourcetype >::result().
template<typename P_sourcetype > T_sourcetype ReduceMinIndex< P_sourcetype >::min_ protected
Referenced by ReduceMinIndex< P_sourcetype >::operator()(), and ReduceMinIndex< P_sourcetype >::reset().
template<typename P_sourcetype > const bool ReduceMinIndex< P_sourcetype >::needIndex = true static
The documentation for this class was generated from the following file:
blitz/reduce.h