blitz: Toeplitz Class Reference
Toeplitz Class Reference
#include <mattoep.h>
Public Types
typedef ToeplitzIterator T_iterator
Public Member Functions
Toeplitz ()
Toeplitz (unsigned rows, unsigned cols)
unsigned columns () const
unsigned coordToOffset (unsigned i, unsigned j) const
unsigned firstInRow (unsigned i) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
unsigned lastInRow (const unsigned) const
unsigned firstInCol (const unsigned) const
unsigned lastInCol (const unsigned) const
bool inRange (const unsigned i, const unsigned j) const
unsigned numElements () const
unsigned rows () const
void resize (const unsigned rows, const unsigned cols)
Public Member Functions inherited from GeneralMatrix
GeneralMatrix ()
GeneralMatrix (unsigned rows, unsigned cols)
unsigned firstInRow (unsigned i) const
unsigned lastInRow (unsigned i) const
unsigned firstInCol (unsigned j) const
unsigned lastInCol (unsigned j) const
unsigned numElements () const
Public Member Functions inherited from AsymmetricMatrix
AsymmetricMatrix ()
AsymmetricMatrix (unsigned rows, unsigned cols)
unsigned columns () const
unsigned cols () const
bool inRange (const unsigned i, const unsigned j) const
void resize (unsigned rows, unsigned cols)
unsigned rows () const
Private Attributes
unsigned rows_
unsigned cols_
Additional Inherited Members
Protected Attributes inherited from AsymmetricMatrix
unsigned rows_
unsigned cols_
Member Typedef Documentation
typedef ToeplitzIterator Toeplitz::T_iterator
Constructor & Destructor Documentation
Toeplitz::Toeplitz () inline
Toeplitz::Toeplitz (unsigned rows, unsigned cols) inline
Member Function Documentation
unsigned Toeplitz::columns () const inline
References cols_.
unsigned Toeplitz::coordToOffset (unsigned i, unsigned j) const inline
References inRange(), and j.
Referenced by get().
unsigned Toeplitz::firstInCol (const unsigned) const inline
unsigned Toeplitz::firstInRow (unsigned i) const inline
template<typename T_numtype > T_numtype Toeplitz::get (const T_numtype *restrict data, unsigned i, unsigned j) const inline
References coordToOffset(), i, inRange(), and j.
template<typename T_numtype > T_numtype& Toeplitz::get (T_numtype *restrict data, unsigned i, unsigned j) inline
References coordToOffset(), i, inRange(), and j.
bool Toeplitz::inRange (const unsigned i, const unsigned j) const inline
References cols_, and rows_.
Referenced by coordToOffset(), and get().
unsigned Toeplitz::lastInCol (const unsigned) const inline
References rows_.
unsigned Toeplitz::lastInRow (const unsigned) const inline
References cols_.
unsigned Toeplitz::numElements () const inline
References cols_, and rows_.
void Toeplitz::resize (const unsigned rows, const unsigned cols) inline
References AsymmetricMatrix::cols(), cols_, rows(), and rows_.
unsigned Toeplitz::rows () const inline
References rows_.
Referenced by resize().
Member Data Documentation
unsigned Toeplitz::cols_ private
Referenced by columns(), inRange(), lastInRow(), numElements(), and resize().
unsigned Toeplitz::rows_ private
Referenced by inRange(), lastInCol(), numElements(), resize(), and rows().
The documentation for this class was generated from the following file:
blitz/mattoep.h