blitz: ReduceMinIndexVector< P_sourcetype, N > Class Template Reference
ReduceMinIndexVector< P_sourcetype, N > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef TinyVector< int, N > T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceMinIndexVector ()
ReduceMinIndexVector (T_resulttype min)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype, int)
bool operator() (T_sourcetype x, const TinyVector< int, N > &index)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool canProvideInitialValue = false
Protected Attributes
T_sourcetype min_
TinyVector< int, N > index_
Member Typedef Documentation
template<typename P_sourcetype , int N> typedef T_resulttype ReduceMinIndexVector< P_sourcetype, N >::T_numtype
template<typename P_sourcetype , int N> typedef TinyVector<int,N> ReduceMinIndexVector< P_sourcetype, N >::T_resulttype
template<typename P_sourcetype , int N> typedef P_sourcetype ReduceMinIndexVector< P_sourcetype, N >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype , int N> ReduceMinIndexVector< P_sourcetype, N >::ReduceMinIndexVector () inline
References ReduceMinIndexVector< P_sourcetype, N >::reset().
template<typename P_sourcetype , int N> ReduceMinIndexVector< P_sourcetype, N >::ReduceMinIndexVector (T_resulttype min) inline
References ReduceMinIndexVector< P_sourcetype, N >::reset().
Member Function Documentation
template<typename P_sourcetype , int N> static const char* ReduceMinIndexVector< P_sourcetype, N >::name () inline static
template<typename P_sourcetype , int N> bool ReduceMinIndexVector< P_sourcetype, N >::operator() (T_sourcetype x) inline
template<typename P_sourcetype , int N> bool ReduceMinIndexVector< P_sourcetype, N >::operator() (T_sourcetype , int) inline
template<typename P_sourcetype , int N> bool ReduceMinIndexVector< P_sourcetype, N >::operator() (T_sourcetype x, const TinyVector< int, N > & index) inline
References ReduceMinIndexVector< P_sourcetype, N >::index_, and ReduceMinIndexVector< P_sourcetype, N >::min_.
template<typename P_sourcetype , int N> void ReduceMinIndexVector< P_sourcetype, N >::reset () inline
References ReduceMinIndexVector< P_sourcetype, N >::index_, and ReduceMinIndexVector< P_sourcetype, N >::min_.
Referenced by ReduceMinIndexVector< P_sourcetype, N >::ReduceMinIndexVector(), and ReduceMinIndexVector< P_sourcetype, N >::reset().
template<typename P_sourcetype , int N> void ReduceMinIndexVector< P_sourcetype, N >::reset (T_resulttype) inline
References ReduceMinIndexVector< P_sourcetype, N >::reset().
template<typename P_sourcetype , int N> T_resulttype ReduceMinIndexVector< P_sourcetype, N >::result (int) inline
References ReduceMinIndexVector< P_sourcetype, N >::index_.
Member Data Documentation
template<typename P_sourcetype , int N> const bool ReduceMinIndexVector< P_sourcetype, N >::canProvideInitialValue = false static
template<typename P_sourcetype , int N> TinyVector<int,N> ReduceMinIndexVector< P_sourcetype, N >::index_ protected
Referenced by ReduceMinIndexVector< P_sourcetype, N >::operator()(), ReduceMinIndexVector< P_sourcetype, N >::reset(), and ReduceMinIndexVector< P_sourcetype, N >::result().
template<typename P_sourcetype , int N> T_sourcetype ReduceMinIndexVector< P_sourcetype, N >::min_ protected
Referenced by ReduceMinIndexVector< P_sourcetype, N >::operator()(), and ReduceMinIndexVector< P_sourcetype, N >::reset().
The documentation for this class was generated from the following file:
blitz/reduce.h