blitz: VectorPickIter< P_numtype > Class Template Reference
VectorPickIter< P_numtype > Class Template Reference
#include <vecpick.h>
Public Types
typedef P_numtype T_numtype
Public Member Functions
VectorPickIter (VectorPick< T_numtype > &x)
T_numtype operator[] (int i) const
T_numtype & operator[] (int i)
int length (int) const
int _bz_suggestLength () const
bool isUnitStride () const
bool _bz_hasFastAccess () const
T_numtype _bz_fastAccess (int i) const
T_numtype & _bz_fastAccess (int i)
Static Public Attributes
static const int _bz_staticLengthCount = 0
static const int _bz_dynamicLengthCount = 1
static const int _bz_staticLength = 0
Private Attributes
T_numtype *restrict data_
int dataStride_
const int *restrict index_
int indexStride_
int length_
Member Typedef Documentation
template<typename P_numtype> typedef P_numtype VectorPickIter< P_numtype >::T_numtype
Constructor & Destructor Documentation
template<typename P_numtype> VectorPickIter< P_numtype >::VectorPickIter (VectorPick< T_numtype > & x) inline explicit
References VectorPick< P_numtype >::indexSet(), Vector< P_numtype >::length(), Vector< P_numtype >::stride(), and VectorPick< P_numtype >::vector().
Member Function Documentation
template<typename P_numtype> T_numtype VectorPickIter< P_numtype >::_bz_fastAccess (int i) const inline
References i.
template<typename P_numtype> T_numtype& VectorPickIter< P_numtype >::_bz_fastAccess (int i) inline
References i.
template<typename P_numtype> bool VectorPickIter< P_numtype >::_bz_hasFastAccess () const inline
template<typename P_numtype> int VectorPickIter< P_numtype >::_bz_suggestLength () const inline
template<typename P_numtype> bool VectorPickIter< P_numtype >::isUnitStride () const inline
template<typename P_numtype> int VectorPickIter< P_numtype >::length (int) const inline
template<typename P_numtype> T_numtype VectorPickIter< P_numtype >::operator[] (int i) const inline
template<typename P_numtype> T_numtype& VectorPickIter< P_numtype >::operator[] (int i) inline
Member Data Documentation
template<typename P_numtype> const int VectorPickIter< P_numtype >::_bz_dynamicLengthCount = 1 static
template<typename P_numtype> const int VectorPickIter< P_numtype >::_bz_staticLength = 0 static
template<typename P_numtype> const int VectorPickIter< P_numtype >::_bz_staticLengthCount = 0 static
template<typename P_numtype> T_numtype* restrict VectorPickIter< P_numtype >::data_ private
template<typename P_numtype> int VectorPickIter< P_numtype >::dataStride_ private
template<typename P_numtype> const int* restrict VectorPickIter< P_numtype >::index_ private
template<typename P_numtype> int VectorPickIter< P_numtype >::indexStride_ private
template<typename P_numtype> int VectorPickIter< P_numtype >::length_ private
The documentation for this class was generated from the following files:
blitz/vecpick.h
blitz/vecpickiter.h