blitz: ReduceAny< P_sourcetype > Class Template Reference
ReduceAny< P_sourcetype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef bool T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceAny ()
ReduceAny (T_resulttype initialValue)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, int)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = false
static const bool canProvideInitialValue = false
Protected Attributes
T_resulttype any_
Member Typedef Documentation
template<typename P_sourcetype > typedef T_resulttype ReduceAny< P_sourcetype >::T_numtype
template<typename P_sourcetype > typedef bool ReduceAny< P_sourcetype >::T_resulttype
template<typename P_sourcetype > typedef P_sourcetype ReduceAny< P_sourcetype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype > ReduceAny< P_sourcetype >::ReduceAny () inline
References ReduceAny< P_sourcetype >::reset().
template<typename P_sourcetype > ReduceAny< P_sourcetype >::ReduceAny (T_resulttype initialValue) inline
References ReduceAny< P_sourcetype >::reset().
Member Function Documentation
template<typename P_sourcetype > static const char* ReduceAny< P_sourcetype >::name () inline static
template<typename P_sourcetype > bool ReduceAny< P_sourcetype >::operator() (T_sourcetype x) inline
References ReduceAny< P_sourcetype >::any_.
template<typename P_sourcetype > bool ReduceAny< P_sourcetype >::operator() (T_sourcetype x, int) inline
References ReduceAny< P_sourcetype >::any_.
template<typename P_sourcetype > void ReduceAny< P_sourcetype >::reset () inline
References ReduceAny< P_sourcetype >::any_.
Referenced by ReduceAny< P_sourcetype >::ReduceAny(), and ReduceAny< P_sourcetype >::reset().
template<typename P_sourcetype > void ReduceAny< P_sourcetype >::reset (T_resulttype) inline
References ReduceAny< P_sourcetype >::reset().
template<typename P_sourcetype > T_resulttype ReduceAny< P_sourcetype >::result (int) inline
References ReduceAny< P_sourcetype >::any_.
Member Data Documentation
template<typename P_sourcetype > T_resulttype ReduceAny< P_sourcetype >::any_ protected
Referenced by ReduceAny< P_sourcetype >::operator()(), ReduceAny< P_sourcetype >::reset(), and ReduceAny< P_sourcetype >::result().
template<typename P_sourcetype > const bool ReduceAny< P_sourcetype >::canProvideInitialValue = false static
template<typename P_sourcetype > const bool ReduceAny< P_sourcetype >::needIndex = false static
The documentation for this class was generated from the following file:
blitz/reduce.h