blitz: LowerTriangular Class Reference
LowerTriangular Class Reference
#include <matltri.h>
Public Types
typedef LowerTriangularIterator T_iterator
Public Member Functions
LowerTriangular ()
LowerTriangular (unsigned size)
LowerTriangular (unsigned rows, unsigned cols)
unsigned columns () const
unsigned coordToOffset (unsigned i, unsigned j) const
unsigned firstInRow (unsigned i) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
unsigned lastInRow (unsigned i) const
unsigned firstInCol (unsigned j) const
unsigned lastInCol (unsigned j) const
bool inRange (unsigned i, unsigned j) const
unsigned numElements () const
unsigned rows () const
void resize (unsigned size)
void resize (unsigned rows, unsigned cols)
Private Attributes
unsigned size_
Member Typedef Documentation
typedef LowerTriangularIterator LowerTriangular::T_iterator
Constructor & Destructor Documentation
LowerTriangular::LowerTriangular () inline
LowerTriangular::LowerTriangular (unsigned size) inline
LowerTriangular::LowerTriangular (unsigned rows, unsigned cols) inline
Member Function Documentation
unsigned LowerTriangular::columns () const inline
References size_.
unsigned LowerTriangular::coordToOffset (unsigned i, unsigned j) const inline
References inRange().
Referenced by get().
unsigned LowerTriangular::firstInCol (unsigned j) const inline
References j.
unsigned LowerTriangular::firstInRow (unsigned i) const inline
template<typename T_numtype > T_numtype LowerTriangular::get (const T_numtype *restrict data, unsigned i, unsigned j) const inline
References coordToOffset(), i, inRange(), j, and ZeroElement< P_numtype >::zero().
template<typename T_numtype > T_numtype& LowerTriangular::get (T_numtype *restrict data, unsigned i, unsigned j) inline
References coordToOffset(), i, inRange(), j, and ZeroElement< P_numtype >::zero().
bool LowerTriangular::inRange (unsigned i, unsigned j) const inline
References size_.
Referenced by coordToOffset(), and get().
unsigned LowerTriangular::lastInCol (unsigned j) const inline
References size_.
unsigned LowerTriangular::lastInRow (unsigned i) const inline
References i.
unsigned LowerTriangular::numElements () const inline
References size_.
void LowerTriangular::resize (unsigned size) inline
References size_.
void LowerTriangular::resize (unsigned rows, unsigned cols) inline
References rows(), and size_.
unsigned LowerTriangular::rows () const inline
References size_.
Referenced by resize().
Member Data Documentation
unsigned LowerTriangular::size_ private
Referenced by columns(), inRange(), lastInCol(), numElements(), resize(), and rows().
The documentation for this class was generated from the following file:
blitz/matltri.h