blitz: ReduceFirst< P_sourcetype > Class Template Reference
ReduceFirst< P_sourcetype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef int T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceFirst ()
ReduceFirst (T_resulttype)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, int index)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = true
static const bool canProvideInitialValue = false
Protected Attributes
int index_
Member Typedef Documentation
template<typename P_sourcetype > typedef T_resulttype ReduceFirst< P_sourcetype >::T_numtype
template<typename P_sourcetype > typedef int ReduceFirst< P_sourcetype >::T_resulttype
template<typename P_sourcetype > typedef P_sourcetype ReduceFirst< P_sourcetype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype > ReduceFirst< P_sourcetype >::ReduceFirst () inline
References ReduceFirst< P_sourcetype >::reset().
template<typename P_sourcetype > ReduceFirst< P_sourcetype >::ReduceFirst (T_resulttype) inline
Member Function Documentation
template<typename P_sourcetype > static const char* ReduceFirst< P_sourcetype >::name () inline static
template<typename P_sourcetype > bool ReduceFirst< P_sourcetype >::operator() (T_sourcetype x) inline
template<typename P_sourcetype > bool ReduceFirst< P_sourcetype >::operator() (T_sourcetype x, int index) inline
References ReduceFirst< P_sourcetype >::index_.
template<typename P_sourcetype > void ReduceFirst< P_sourcetype >::reset () inline
References ReduceFirst< P_sourcetype >::index_.
Referenced by ReduceFirst< P_sourcetype >::ReduceFirst(), and ReduceFirst< P_sourcetype >::reset().
template<typename P_sourcetype > void ReduceFirst< P_sourcetype >::reset (T_resulttype) inline
References ReduceFirst< P_sourcetype >::reset().
template<typename P_sourcetype > T_resulttype ReduceFirst< P_sourcetype >::result (int) inline
References ReduceFirst< P_sourcetype >::index_.
Member Data Documentation
template<typename P_sourcetype > const bool ReduceFirst< P_sourcetype >::canProvideInitialValue = false static
template<typename P_sourcetype > int ReduceFirst< P_sourcetype >::index_ protected
Referenced by ReduceFirst< P_sourcetype >::operator()(), ReduceFirst< P_sourcetype >::reset(), and ReduceFirst< P_sourcetype >::result().
template<typename P_sourcetype > const bool ReduceFirst< P_sourcetype >::needIndex = true static
The documentation for this class was generated from the following file:
blitz/reduce.h