blitz: ColumnMajor Class Reference
ColumnMajor Class Reference
#include <matgen.h>
Public Member Functions
ColumnMajor ()
ColumnMajor (unsigned rows, unsigned cols)
unsigned coordToOffset (unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype get (const T_numtype *restrict data, unsigned i, unsigned j) const
template<typename T_numtype >
T_numtype & get (T_numtype *restrict data, unsigned i, unsigned j)
Public Member Functions inherited from GeneralMatrix
GeneralMatrix ()
GeneralMatrix (unsigned rows, unsigned cols)
unsigned firstInRow (unsigned i) const
unsigned lastInRow (unsigned i) const
unsigned firstInCol (unsigned j) const
unsigned lastInCol (unsigned j) const
unsigned numElements () const
Public Member Functions inherited from AsymmetricMatrix
AsymmetricMatrix ()
AsymmetricMatrix (unsigned rows, unsigned cols)
unsigned columns () const
unsigned cols () const
bool inRange (const unsigned i, const unsigned j) const
void resize (unsigned rows, unsigned cols)
unsigned rows () const
Additional Inherited Members
Protected Attributes inherited from AsymmetricMatrix
unsigned rows_
unsigned cols_
Constructor & Destructor Documentation
ColumnMajor::ColumnMajor () inline
ColumnMajor::ColumnMajor (unsigned rows, unsigned cols) inline
Member Function Documentation
unsigned ColumnMajor::coordToOffset (unsigned i, unsigned j) const inline
References i, and AsymmetricMatrix::rows_.
Referenced by get().
template<typename T_numtype > T_numtype ColumnMajor::get (const T_numtype *restrict data, unsigned i, unsigned j) const inline
References coordToOffset(), i, AsymmetricMatrix::inRange(), and j.
template<typename T_numtype > T_numtype& ColumnMajor::get (T_numtype *restrict data, unsigned i, unsigned j) inline
References coordToOffset(), i, AsymmetricMatrix::inRange(), and j.
The documentation for this class was generated from the following file:
blitz/matgen.h