blitz: ReduceAll< P_sourcetype > Class Template Reference
ReduceAll< P_sourcetype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef bool T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceAll ()
ReduceAll (T_resulttype initialValue)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, int)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = false
static const bool canProvideInitialValue = false
Protected Attributes
T_resulttype all_
Member Typedef Documentation
template<typename P_sourcetype > typedef T_resulttype ReduceAll< P_sourcetype >::T_numtype
template<typename P_sourcetype > typedef bool ReduceAll< P_sourcetype >::T_resulttype
template<typename P_sourcetype > typedef P_sourcetype ReduceAll< P_sourcetype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype > ReduceAll< P_sourcetype >::ReduceAll () inline
References ReduceAll< P_sourcetype >::reset().
template<typename P_sourcetype > ReduceAll< P_sourcetype >::ReduceAll (T_resulttype initialValue) inline
References ReduceAll< P_sourcetype >::reset().
Member Function Documentation
template<typename P_sourcetype > static const char* ReduceAll< P_sourcetype >::name () inline static
template<typename P_sourcetype > bool ReduceAll< P_sourcetype >::operator() (T_sourcetype x) inline
References ReduceAll< P_sourcetype >::all_.
template<typename P_sourcetype > bool ReduceAll< P_sourcetype >::operator() (T_sourcetype x, int) inline
References ReduceAll< P_sourcetype >::all_.
template<typename P_sourcetype > void ReduceAll< P_sourcetype >::reset () inline
References ReduceAll< P_sourcetype >::all_.
Referenced by ReduceAll< P_sourcetype >::ReduceAll(), and ReduceAll< P_sourcetype >::reset().
template<typename P_sourcetype > void ReduceAll< P_sourcetype >::reset (T_resulttype) inline
References ReduceAll< P_sourcetype >::reset().
template<typename P_sourcetype > T_resulttype ReduceAll< P_sourcetype >::result (int) inline
References ReduceAll< P_sourcetype >::all_.
Member Data Documentation
template<typename P_sourcetype > T_resulttype ReduceAll< P_sourcetype >::all_ protected
Referenced by ReduceAll< P_sourcetype >::operator()(), ReduceAll< P_sourcetype >::reset(), and ReduceAll< P_sourcetype >::result().
template<typename P_sourcetype > const bool ReduceAll< P_sourcetype >::canProvideInitialValue = false static
template<typename P_sourcetype > const bool ReduceAll< P_sourcetype >::needIndex = false static
The documentation for this class was generated from the following file:
blitz/reduce.h