blitz: AsymmetricMatrix Class Reference
AsymmetricMatrix Class Reference
#include <mstruct.h>
Public Member Functions
AsymmetricMatrix ()
AsymmetricMatrix (unsigned rows, unsigned cols)
unsigned columns () const
unsigned cols () const
bool inRange (const unsigned i, const unsigned j) const
void resize (unsigned rows, unsigned cols)
unsigned rows () const
Protected Attributes
unsigned rows_
unsigned cols_
Constructor & Destructor Documentation
AsymmetricMatrix::AsymmetricMatrix () inline
AsymmetricMatrix::AsymmetricMatrix (unsigned rows, unsigned cols) inline
Member Function Documentation
unsigned AsymmetricMatrix::cols () const inline
References cols_.
Referenced by resize(), and Toeplitz::resize().
unsigned AsymmetricMatrix::columns () const inline
References cols_.
bool AsymmetricMatrix::inRange (const unsigned i, const unsigned j) const inline
References cols_, and rows_.
Referenced by RowMajor::get(), and ColumnMajor::get().
void AsymmetricMatrix::resize (unsigned rows, unsigned cols) inline
References cols(), cols_, rows(), and rows_.
unsigned AsymmetricMatrix::rows () const inline
References rows_.
Referenced by resize().
Member Data Documentation
unsigned AsymmetricMatrix::cols_ protected
Referenced by cols(), columns(), RowMajor::coordToOffset(), inRange(), and resize().
unsigned AsymmetricMatrix::rows_ protected
Referenced by ColumnMajor::coordToOffset(), inRange(), resize(), and rows().
The documentation for this class was generated from the following file:
blitz/mstruct.h