blitz: ReduceProduct< P_sourcetype, P_resulttype > Class Template Reference
ReduceProduct< P_sourcetype, P_resulttype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef P_resulttype T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceProduct ()
ReduceProduct (T_resulttype initialValue)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, int)
T_resulttype result (int)
void reset ()
void reset (T_resulttype initialValue)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = false
static const bool canProvideInitialValue = true
Protected Attributes
T_resulttype product_
Member Typedef Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> typedef T_resulttype ReduceProduct< P_sourcetype, P_resulttype >::T_numtype
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> typedef P_resulttype ReduceProduct< P_sourcetype, P_resulttype >::T_resulttype
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> typedef P_sourcetype ReduceProduct< P_sourcetype, P_resulttype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> ReduceProduct< P_sourcetype, P_resulttype >::ReduceProduct () inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> ReduceProduct< P_sourcetype, P_resulttype >::ReduceProduct (T_resulttype initialValue) inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
Member Function Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> static const char* ReduceProduct< P_sourcetype, P_resulttype >::name () inline static
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> bool ReduceProduct< P_sourcetype, P_resulttype >::operator() (T_sourcetype x) inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> bool ReduceProduct< P_sourcetype, P_resulttype >::operator() (T_sourcetype x, int) inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> void ReduceProduct< P_sourcetype, P_resulttype >::reset () inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> void ReduceProduct< P_sourcetype, P_resulttype >::reset (T_resulttype initialValue) inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> T_resulttype ReduceProduct< P_sourcetype, P_resulttype >::result (int) inline
References ReduceProduct< P_sourcetype, P_resulttype >::product_.
Member Data Documentation
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> const bool ReduceProduct< P_sourcetype, P_resulttype >::canProvideInitialValue = true static
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> const bool ReduceProduct< P_sourcetype, P_resulttype >::needIndex = false static
template<typename P_sourcetype , typename P_resulttype = BZ_SUMTYPE(P_sourcetype)> T_resulttype ReduceProduct< P_sourcetype, P_resulttype >::product_ protected
Referenced by ReduceProduct< P_sourcetype, P_resulttype >::operator()(), ReduceProduct< P_sourcetype, P_resulttype >::ReduceProduct(), ReduceProduct< P_sourcetype, P_resulttype >::reset(), and ReduceProduct< P_sourcetype, P_resulttype >::result().
The documentation for this class was generated from the following file:
blitz/reduce.h