blitz: ZeroElement< P_numtype > Class Template Reference
ZeroElement< P_numtype > Class Template Reference
#include <zero.h>
Public Types
typedef P_numtype T_numtype
Static Public Member Functions
static T_numtype & zero ()
Static Private Attributes
static T_numtype zero_ = 0
Member Typedef Documentation
template<typename P_numtype > typedef P_numtype ZeroElement< P_numtype >::T_numtype
Member Function Documentation
template<typename P_numtype > static T_numtype& ZeroElement< P_numtype >::zero () inline static
Referenced by Diagonal::get(), UpperTriangular::get(), and LowerTriangular::get().
Member Data Documentation
template<typename P_numtype > P_numtype ZeroElement< P_numtype >::zero_ = 0 static private
The documentation for this class was generated from the following file:
blitz/zero.h