blitz: ReduceMaxIndex< P_sourcetype > Class Template Reference
ReduceMaxIndex< P_sourcetype > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef int T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceMaxIndex ()
ReduceMaxIndex (T_resulttype max)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, int index)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool needIndex = true
static const bool canProvideInitialValue = false
Protected Attributes
T_sourcetype max_
int index_
Member Typedef Documentation
template<typename P_sourcetype > typedef T_resulttype ReduceMaxIndex< P_sourcetype >::T_numtype
template<typename P_sourcetype > typedef int ReduceMaxIndex< P_sourcetype >::T_resulttype
template<typename P_sourcetype > typedef P_sourcetype ReduceMaxIndex< P_sourcetype >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype > ReduceMaxIndex< P_sourcetype >::ReduceMaxIndex () inline
References ReduceMaxIndex< P_sourcetype >::reset().
template<typename P_sourcetype > ReduceMaxIndex< P_sourcetype >::ReduceMaxIndex (T_resulttype max) inline
References ReduceMaxIndex< P_sourcetype >::reset().
Member Function Documentation
template<typename P_sourcetype > static const char* ReduceMaxIndex< P_sourcetype >::name () inline static
template<typename P_sourcetype > bool ReduceMaxIndex< P_sourcetype >::operator() (T_sourcetype x) inline
template<typename P_sourcetype > bool ReduceMaxIndex< P_sourcetype >::operator() (T_sourcetype x, int index) inline
References ReduceMaxIndex< P_sourcetype >::index_, and ReduceMaxIndex< P_sourcetype >::max_.
template<typename P_sourcetype > void ReduceMaxIndex< P_sourcetype >::reset () inline
References ReduceMaxIndex< P_sourcetype >::index_, and ReduceMaxIndex< P_sourcetype >::max_.
Referenced by ReduceMaxIndex< P_sourcetype >::ReduceMaxIndex(), and ReduceMaxIndex< P_sourcetype >::reset().
template<typename P_sourcetype > void ReduceMaxIndex< P_sourcetype >::reset (T_resulttype) inline
References ReduceMaxIndex< P_sourcetype >::reset().
template<typename P_sourcetype > T_resulttype ReduceMaxIndex< P_sourcetype >::result (int) inline
References ReduceMaxIndex< P_sourcetype >::index_.
Member Data Documentation
template<typename P_sourcetype > const bool ReduceMaxIndex< P_sourcetype >::canProvideInitialValue = false static
template<typename P_sourcetype > int ReduceMaxIndex< P_sourcetype >::index_ protected
Referenced by ReduceMaxIndex< P_sourcetype >::operator()(), ReduceMaxIndex< P_sourcetype >::reset(), and ReduceMaxIndex< P_sourcetype >::result().
template<typename P_sourcetype > T_sourcetype ReduceMaxIndex< P_sourcetype >::max_ protected
Referenced by ReduceMaxIndex< P_sourcetype >::operator()(), and ReduceMaxIndex< P_sourcetype >::reset().
template<typename P_sourcetype > const bool ReduceMaxIndex< P_sourcetype >::needIndex = true static
The documentation for this class was generated from the following file:
blitz/reduce.h