blitz: Gamma< T, IRNG, stateTag > Class Template Reference
Gamma< T, IRNG, stateTag > Class Template Reference
#include <gamma.h>
Public Types
typedef T T_numtype
Public Types inherited from UniformOpen< T, IRNG, stateTag >
typedef T T_numtype
Public Member Functions
Gamma ()
Gamma (T mean)
T random ()
void setMean (T mean)
Public Member Functions inherited from UniformOpen< T, IRNG, stateTag >
T random ()
T getUniform ()
Protected Member Functions
T ranf ()
T snorm ()
T sexpo ()
T fsign (T num, T sign)
Protected Attributes
NormalUnit< T, IRNG, sharedState > normal_
ExponentialUnit< T, IRNG,
sharedState > exponential_
T a
Member Typedef Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> typedef T Gamma< T, IRNG, stateTag >::T_numtype
Constructor & Destructor Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Gamma< T, IRNG, stateTag >::Gamma () inline
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> Gamma< T, IRNG, stateTag >::Gamma (T mean) inline
Member Function Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::fsign (T num, T sign) inline protected
template<typename T , typename IRNG , typename stateTag > T Gamma< T, IRNG, stateTag >::random (void)
References a, b, p, q, r, s, and t.
Referenced by ChiSquare< T, IRNG, stateTag >::sgamma().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::ranf () inline protected
References UniformOpen< T, IRNG, stateTag >::random().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> void Gamma< T, IRNG, stateTag >::setMean (T mean) inline
References a.
Referenced by ChiSquare< T, IRNG, stateTag >::setDF().
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::sexpo () inline protected
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::snorm () inline protected
Member Data Documentation
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> T Gamma< T, IRNG, stateTag >::a protected
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> ExponentialUnit<T,IRNG,sharedState> Gamma< T, IRNG, stateTag >::exponential_ protected
template<typename T = double, typename IRNG = defaultIRNG, typename stateTag = defaultState> NormalUnit<T,IRNG,sharedState> Gamma< T, IRNG, stateTag >::normal_ protected
The documentation for this class was generated from the following file:
random/gamma.h