blitz: ReduceMaxIndexVector< P_sourcetype, N_rank > Class Template Reference
ReduceMaxIndexVector< P_sourcetype, N_rank > Class Template Reference
#include <reduce.h>
Public Types
typedef P_sourcetype T_sourcetype
typedef TinyVector< int, N_rank > T_resulttype
typedef T_resulttype T_numtype
Public Member Functions
ReduceMaxIndexVector ()
ReduceMaxIndexVector (T_resulttype max)
bool operator() (T_sourcetype x)
bool operator() (T_sourcetype x, const TinyVector< int, N_rank > &index)
T_resulttype result (int)
void reset ()
void reset (T_resulttype)
Static Public Member Functions
static const char * name ()
Static Public Attributes
static const bool canProvideInitialValue = false
Protected Attributes
T_sourcetype max_
TinyVector< int, N_rank > index_
Member Typedef Documentation
template<typename P_sourcetype , int N_rank> typedef T_resulttype ReduceMaxIndexVector< P_sourcetype, N_rank >::T_numtype
template<typename P_sourcetype , int N_rank> typedef TinyVector<int,N_rank> ReduceMaxIndexVector< P_sourcetype, N_rank >::T_resulttype
template<typename P_sourcetype , int N_rank> typedef P_sourcetype ReduceMaxIndexVector< P_sourcetype, N_rank >::T_sourcetype
Constructor & Destructor Documentation
template<typename P_sourcetype , int N_rank> ReduceMaxIndexVector< P_sourcetype, N_rank >::ReduceMaxIndexVector () inline
References ReduceMaxIndexVector< P_sourcetype, N_rank >::reset().
template<typename P_sourcetype , int N_rank> ReduceMaxIndexVector< P_sourcetype, N_rank >::ReduceMaxIndexVector (T_resulttype max) inline
References ReduceMaxIndexVector< P_sourcetype, N_rank >::reset().
Member Function Documentation
template<typename P_sourcetype , int N_rank> static const char* ReduceMaxIndexVector< P_sourcetype, N_rank >::name () inline static
template<typename P_sourcetype , int N_rank> bool ReduceMaxIndexVector< P_sourcetype, N_rank >::operator() (T_sourcetype x) inline
template<typename P_sourcetype , int N_rank> bool ReduceMaxIndexVector< P_sourcetype, N_rank >::operator() (T_sourcetype x, const TinyVector< int, N_rank > & index) inline
References ReduceMaxIndexVector< P_sourcetype, N_rank >::index_, and ReduceMaxIndexVector< P_sourcetype, N_rank >::max_.
template<typename P_sourcetype , int N_rank> void ReduceMaxIndexVector< P_sourcetype, N_rank >::reset () inline
References ReduceMaxIndexVector< P_sourcetype, N_rank >::index_, and ReduceMaxIndexVector< P_sourcetype, N_rank >::max_.
Referenced by ReduceMaxIndexVector< P_sourcetype, N_rank >::ReduceMaxIndexVector(), and ReduceMaxIndexVector< P_sourcetype, N_rank >::reset().
template<typename P_sourcetype , int N_rank> void ReduceMaxIndexVector< P_sourcetype, N_rank >::reset (T_resulttype) inline
References ReduceMaxIndexVector< P_sourcetype, N_rank >::reset().
template<typename P_sourcetype , int N_rank> T_resulttype ReduceMaxIndexVector< P_sourcetype, N_rank >::result (int) inline
References ReduceMaxIndexVector< P_sourcetype, N_rank >::index_.
Member Data Documentation
template<typename P_sourcetype , int N_rank> const bool ReduceMaxIndexVector< P_sourcetype, N_rank >::canProvideInitialValue = false static
template<typename P_sourcetype , int N_rank> TinyVector<int,N_rank> ReduceMaxIndexVector< P_sourcetype, N_rank >::index_ protected
Referenced by ReduceMaxIndexVector< P_sourcetype, N_rank >::operator()(), ReduceMaxIndexVector< P_sourcetype, N_rank >::reset(), and ReduceMaxIndexVector< P_sourcetype, N_rank >::result().
template<typename P_sourcetype , int N_rank> T_sourcetype ReduceMaxIndexVector< P_sourcetype, N_rank >::max_ protected
Referenced by ReduceMaxIndexVector< P_sourcetype, N_rank >::operator()(), and ReduceMaxIndexVector< P_sourcetype, N_rank >::reset().
The documentation for this class was generated from the following file:
blitz/reduce.h